### ISSUE TITLE
Release v1.3.1 is missing artifact

### ISSUE THREAD

**Issue by dislogical** [jorgenpt/teamcity-ugs-status-publisher#1]
Looks like [this release](https://github.com/jorgenpt/teamcity-ugs-status-publisher/releases/tag/v1.3.1) is missing it's artifact, while [v1.3.0](https://github.com/jorgenpt/teamcity-ugs-status-publisher/releases/tag/v1.3.0) has a built zip attached.

**Comment by jorgenpt** [comment]
@ColdenCullen Thanks! I have uploaded it now. I should probably automate that part of the process -- it's just downloading the artifact from the GitHub Actions run and re-uploading it to the Release section, but clearly it's error prone 😅
